/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_solving_MARCORBSolver */

#ifndef _Included_jmarc_solving_MARCORBSolver
#define _Included_jmarc_solving_MARCORBSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_solving_MARCORBSolver
 * Method:    createNativeObject
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_solving_MARCORBSolver_createNativeObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     jmarc_solving_MARCORBSolver
 * Method:    solve
 * Signature: ()Ljmarc/modeling/MARCSolution;
 */
JNIEXPORT jobject JNICALL Java_jmarc_solving_MARCORBSolver_solve
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_solving_MARCORBSolver
 * Method:    addBootstrapState
 * Signature: (Ljmarc/modeling/MARCState;)V
 */
JNIEXPORT void JNICALL Java_jmarc_solving_MARCORBSolver_addBootstrapState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmarc_solving_MARCORBSolver
 * Method:    bootstrap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmarc_solving_MARCORBSolver_bootstrap
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_solving_MARCORBSolver
 * Method:    getBootstrap
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_jmarc_solving_MARCORBSolver_getBootstrap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
