/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_solving_MARCFirstChoiceHillClimbing */

#ifndef _Included_jmarc_solving_MARCFirstChoiceHillClimbing
#define _Included_jmarc_solving_MARCFirstChoiceHillClimbing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_solving_MARCFirstChoiceHillClimbing
 * Method:    createNativeObject
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_solving_MARCFirstChoiceHillClimbing_createNativeObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
