/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_modeling_MARCSolution */

#ifndef _Included_jmarc_modeling_MARCSolution
#define _Included_jmarc_modeling_MARCSolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_modeling_MARCSolution
 * Method:    createNativeObject
 * Signature: (Ljmarc/modeling/MARCState;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCSolution_createNativeObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmarc_modeling_MARCSolution
 * Method:    getStateSolution
 * Signature: ()Ljmarc/modeling/MARCState;
 */
JNIEXPORT jobject JNICALL Java_jmarc_modeling_MARCSolution_getStateSolution
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
