/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_solving_MARCSimulatedAnnealing */

#ifndef _Included_jmarc_solving_MARCSimulatedAnnealing
#define _Included_jmarc_solving_MARCSimulatedAnnealing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_solving_MARCSimulatedAnnealing
 * Method:    createNativeObject
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_solving_MARCSimulatedAnnealing_createNativeObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     jmarc_solving_MARCSimulatedAnnealing
 * Method:    setTemperature
 * Signature: (Ljmarc/solving/MARCTemperature;)V
 */
JNIEXPORT void JNICALL Java_jmarc_solving_MARCSimulatedAnnealing_setTemperature
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
