/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_modeling_MARCInitStateProblem */

#ifndef _Included_jmarc_modeling_MARCInitStateProblem
#define _Included_jmarc_modeling_MARCInitStateProblem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_modeling_MARCInitStateProblem
 * Method:    createNativeObject
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCInitStateProblem_createNativeObject__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmarc_modeling_MARCInitStateProblem
 * Method:    createNativeObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCInitStateProblem_createNativeObject__Ljava_lang_Object_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     jmarc_modeling_MARCInitStateProblem
 * Method:    getInitialState
 * Signature: ()Ljmarc/modeling/MARCState;
 */
JNIEXPORT jobject JNICALL Java_jmarc_modeling_MARCInitStateProblem_getInitialState
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_modeling_MARCInitStateProblem
 * Method:    setInitialState
 * Signature: (Ljmarc/modeling/MARCState;)V
 */
JNIEXPORT void JNICALL Java_jmarc_modeling_MARCInitStateProblem_setInitialState
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
