/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_solving_MARCSolverMonitor */

#ifndef _Included_jmarc_solving_MARCSolverMonitor
#define _Included_jmarc_solving_MARCSolverMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_solving_MARCSolverMonitor
 * Method:    createNativeObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_solving_MARCSolverMonitor_createNativeObject
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
