/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_modeling_MARCProblem */

#ifndef _Included_jmarc_modeling_MARCProblem
#define _Included_jmarc_modeling_MARCProblem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_modeling_MARCProblem
 * Method:    createNativeObject
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCProblem_createNativeObject__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmarc_modeling_MARCProblem
 * Method:    createNativeObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCProblem_createNativeObject__Ljava_lang_Object_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
