/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_modeling_MARCAction */

#ifndef _Included_jmarc_modeling_MARCAction
#define _Included_jmarc_modeling_MARCAction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_modeling_MARCAction
 * Method:    createNativeObject
 * Signature: (Ljmarc/modeling/MARCProblem;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCAction_createNativeObject
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     jmarc_modeling_MARCAction
 * Method:    getActionProblem
 * Signature: ()Ljmarc/modeling/MARCProblem;
 */
JNIEXPORT jobject JNICALL Java_jmarc_modeling_MARCAction_getActionProblem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
