/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_MARCNativeWrapper */

#ifndef _Included_jmarc_MARCNativeWrapper
#define _Included_jmarc_MARCNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_MARCNativeWrapper
 * Method:    cleanUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jmarc_MARCNativeWrapper_cleanUp
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
