/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_solving_MARCSolver */

#ifndef _Included_jmarc_solving_MARCSolver
#define _Included_jmarc_solving_MARCSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_solving_MARCSolver
 * Method:    getSolverProblem
 * Signature: ()Ljmarc/modeling/MARCProblem;
 */
JNIEXPORT jobject JNICALL Java_jmarc_solving_MARCSolver_getSolverProblem
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_solving_MARCSolver
 * Method:    setSolverProblem
 * Signature: (Ljmarc/modeling/MARCProblem;)V
 */
JNIEXPORT void JNICALL Java_jmarc_solving_MARCSolver_setSolverProblem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmarc_solving_MARCSolver
 * Method:    scheduleAlgorithm
 * Signature: (Ljmarc/solving/MARCAlgorithm;IZ)V
 */
JNIEXPORT void JNICALL Java_jmarc_solving_MARCSolver_scheduleAlgorithm
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     jmarc_solving_MARCSolver
 * Method:    setMonitor
 * Signature: (Ljmarc/solving/MARCSolverMonitor;)V
 */
JNIEXPORT void JNICALL Java_jmarc_solving_MARCSolver_setMonitor
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
