/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_modeling_MARCState */

#ifndef _Included_jmarc_modeling_MARCState
#define _Included_jmarc_modeling_MARCState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_modeling_MARCState
 * Method:    createNativeObject
 * Signature: (Ljmarc/modeling/MARCProblem;)J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCState_createNativeObject__Ljmarc_modeling_MARCProblem_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmarc_modeling_MARCState
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jmarc_modeling_MARCState_createNativeObject__
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_modeling_MARCState
 * Method:    getStateProblem
 * Signature: ()Ljmarc/modeling/MARCProblem;
 */
JNIEXPORT jobject JNICALL Java_jmarc_modeling_MARCState_getStateProblem
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_modeling_MARCState
 * Method:    setStateProblem
 * Signature: (Ljmarc/modeling/MARCProblem;)V
 */
JNIEXPORT void JNICALL Java_jmarc_modeling_MARCState_setStateProblem
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
