/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmarc_solving_MARCSequentialSolver */

#ifndef _Included_jmarc_solving_MARCSequentialSolver
#define _Included_jmarc_solving_MARCSequentialSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmarc_solving_MARCSequentialSolver
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jmarc_solving_MARCSequentialSolver_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     jmarc_solving_MARCSequentialSolver
 * Method:    solve
 * Signature: ()Ljmarc/modeling/MARCSolution;
 */
JNIEXPORT jobject JNICALL Java_jmarc_solving_MARCSequentialSolver_solve
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
